carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.home_page_v2, name="home"),
    path('agregar', views.agregar_page, name="add"),
    path('borrar', views.delete_entry_page, name="delete_entry"),
    path('add_1', views.add_1_page, name="add_1"),
    path('remove_1', views.remove_1_page, name="remove_1"),
    path('old', views.home_page),

]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home_page, name="home"),
    path('snacks/<str:slug>', views.snacks_page, name="snacks_page"),
    path('box/add', views.add_box_to_cart, name="add_boxes"),
    path('product/add', views.add_product_to_cart, name="add_product"),
    path('box/add_special', views.add_special_box_to_cart, name="add_boxes_special"),
    path('box/remove', views.remove_box_from_cart, name="remove_boxes"),
    path('luxury-handmade-chocolates/<str:slug>', views.box_page, name="boxes"),
    path('advent-calendar', views.advent_calendar_page, name="boxes-valentines"),
]

boxes/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from imagekit.models import ImageSpecField

from flavours.models import Flavour, PreBuildFlavour, FlavourChoice
from custom_chocolates.models import UserChocolateDesign
from django.utils.text import slugify


# Create your models here.
def upload_location(instance, filename):
    return "box-size-img/%s/%s" % (instance.id, filename)


class BoxSizeManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class BoxSize(models.Model):
    size = models.PositiveIntegerField()
    weight = models.PositiveIntegerField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    color = models.CharField(max_length=200, null=True, blank=True)
    title = models.CharField(max_length=200, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=20, blank=True, null=True)
    price_id = models.CharField(max_length=200, null=True, blank=True)
    custom_price = models.DecimalField(decimal_places=2, max_digits=20, blank=True, null=True)
    custom_price_id = models.CharField(max_length=200, null=True, blank=True)
    active = models.BooleanField(default=True)
    sold_out = models.BooleanField(default=False)
    custom_chocolates_min = models.PositiveIntegerField(blank=True, null=True, default=1)
    slug = models.SlugField(blank=True)
    special_box = models.BooleanField(default=False)
    valentines_box = models.BooleanField(default=False)
    seo_title = models.CharField(max_length=200, blank=True)
    seo_description = models.TextField(blank=True)
    prebuild_options = models.ManyToManyField(PreBuildFlavour, blank=True, related_name="prebuild_options")

    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    store_image = ProcessedImageField(upload_to=upload_location, null=True, blank=True,
                                      processors=[ResizeToFill(1500, 1500)],
                                      format='JPEG',
                                      options={'quality': 100})

    image = ProcessedImageField(upload_to=upload_location, null=True, blank=True,
                                processors=[ResizeToFill(1500, 1500)],
                                format='JPEG',
                                options={'quality': 100})
    image2 = ProcessedImageField(upload_to=upload_location, null=True, blank=True,
                                 processors=[ResizeToFill(1500, 1500)],
                                 format='JPEG',
                                 options={'quality': 100})
    image3 = ProcessedImageField(upload_to=upload_location, null=True, blank=True,
                                 processors=[ResizeToFill(1500, 1500)],
                                 format='JPEG',
                                 options={'quality': 100})
    image4 = ProcessedImageField(upload_to=upload_location, null=True, blank=True,
                                 processors=[ResizeToFill(1500, 1500)],
                                 format='JPEG',
                                 options={'quality': 100})
    image5 = ProcessedImageField(upload_to=upload_location, null=True, blank=True,
                                 processors=[ResizeToFill(1500, 1500)],
                                 format='JPEG',
                                 options={'quality': 100})

    def __str__(self):
        return self.slug

    objects = BoxSizeManager()

    class Meta:
        ordering = ['size']

    def get_absolute_url(self):
        if self.special_box:
            return f"/shop-now/{self.slug}"
        else:
            return f"/shop-now/luxury-handmade-chocolates/{self.slug}"

        # return f"/shop-now/luxury-handmade-chocolates/box-{self.size}"


    def images(self):
        images = []

        if self.image:
            images.append(self.image)
        if self.image2:
            images.append(self.image2)
        if self.image3:
            images.append(self.image3)
        if self.image4:
            images.append(self.image4)
        if self.image5:
            images.append(self.image5)

        return images

    def save(self, *args, **kwargs):
        # Generate a slug from the title if one is not provided
        if not self.slug:
            self.slug = slugify("Box of {}".format(self.size))
        super().save(*args, **kwargs)


class Box(models.Model):
    PRE_BUILT = "pre_built"
    CUSTOM = "custom"
    PICK_AND_MIX = "pick_and_mix"

    FLAVOURS_FORMAT_CHOICES = (
        (CUSTOM, "Custom"),
        (PRE_BUILT, "Pre-Built"),
        (PICK_AND_MIX, "Pick and Mix"),
    )

    size = models.ForeignKey(BoxSize, on_delete=models.PROTECT, null=True)
    flavour_format = models.CharField(max_length=30, choices=FLAVOURS_FORMAT_CHOICES, default=PRE_BUILT)
    pre_built = models.ForeignKey(PreBuildFlavour, on_delete=models.PROTECT, null=True)
    selected_prebuilts = models.ManyToManyField(PreBuildFlavour, blank=True, related_name="selected_prebuilts")
    selected_flavours = models.ManyToManyField(FlavourChoice, blank=True, related_name="selected_flavours")

    custom_design = models.ForeignKey(UserChocolateDesign, blank=True, null=True, on_delete=models.PROTECT)
    custom_chocolates_flavours = models.ManyToManyField(Flavour, blank=True)

    # price_stripe_id = models.CharField(max_length=100, null=True, blank=True)

    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "Box of {} Chocolates, {}".format(self.size, self.flavour_format)

    @property
    def image(self):
        return self.size.image

    @property
    def price(self):
        if self.custom_design:
            return self.size.custom_price
        else:
            return self.size.price

    @property
    def flavours(self):
        if self.flavour_format == Box.PRE_BUILT:
            return self.selected_prebuilts
        elif self.selected_flavours.exists():
            return self.selected_flavours
        elif self.custom_chocolates_flavours.exists():
            return self.custom_chocolates_flavours

    @property
    def get_price_id(self):
        if self.custom_design:
            return self.size.custom_price_id
        else:
            return self.size.price_id

    @property
    def name(self):
        return self.size.name

    @property
    def sold_out(self):
        return self.size.sold_out

products/views.py
from django.shortcuts import render

# Create your views here.

store/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from products.models import Product
from flavours.models import PreBuildFlavour, Flavour, FlavourChoice
from boxes.models import Box, BoxSize
from carts.models import CartEntry
from lots.models import Lot, LotSize
from custom_chocolates.models import UserChocolateDesign
from .models import FLAVOURS, FLAVOUR_FORMAT
VALENTINES_ACTIVE = False

# Create your views here.


def home_page(request):
    qs = BoxSize.objects.filter(active=True, special_box=False)

    snacks = Product.objects.filter(type="snacks", active=True)

    context = {
        "title": "Build your box of CassPea chocolates.",
        "subtitle": "Let us surprise you with our own selection, or choose your own flavours with our Pick and Mix option!",
        "qs": qs,
        "valentines_active": VALENTINES_ACTIVE,
        "snacks": snacks,
    }

    if VALENTINES_ACTIVE:
        valentines_boxes_qs = BoxSize.objects.filter(
            active=True, valentines_box=True)
        context["valentines_boxes_qs"] = valentines_boxes_qs

    return render(request, "store/home.html", context)


def box_page(request, slug=None):
    flavours = Flavour.objects.active()

    box_obj = get_object_or_404(BoxSize, slug=slug, special_box=False)

    context = {
        "size": box_obj.size,
        "flavours": flavours,
        "prebuilds": box_obj.prebuild_options.all(),
        "PRE_BUILT": Box.PRE_BUILT,
        "PICK_AND_MIX": Box.PICK_AND_MIX,
        "FLAVOUR_FORMAT": FLAVOUR_FORMAT,
        "title": box_obj.title,
        "box_obj": box_obj,
    }

    return render(request, "store/box.html", context)


def snacks_page(request, slug=None):
    product = get_object_or_404(Product, slug=slug, type="snacks")
    context = {
        "obj": product,
    }
    return render(request, "store/product.html", context)


def advent_calendar_page(request):
    box_size_qs = BoxSize.objects.filter(slug="Advent-Calendar")

    box_obj = None
    if len(box_size_qs) == 1:
        box_obj = box_size_qs.first()

    flavours_qs = Flavour.objects.active()

    context = {
        "size": box_obj.size,
        "prebuilds": box_obj.prebuild_options.all(),
        "PRE_BUILT": Box.PRE_BUILT,
        "FLAVOUR_FORMAT": FLAVOUR_FORMAT,
        "title": box_obj.title,
        "box_obj": box_obj,
        "flavours_qs": flavours_qs
    }

    return render(request, "store/advent-calendar.html", context)


def valentines_box_page(request, slug=None):
    box_obj = get_object_or_404(BoxSize, slug=slug, special_box=True)
    flavours = Flavour.objects.active()
    valentine_flavours = flavours.filter(valentines_flavour=True)

    context = {
        "size": box_obj.size,
        "flavours": flavours,
        "PRE_BUILT": Box.PRE_BUILT,
        "PICK_AND_MIX": Box.PICK_AND_MIX,
        "FLAVOUR_FORMAT": FLAVOUR_FORMAT,
        "title": box_obj.title,
        "box_obj": box_obj,
        "prebuilds": box_obj.prebuild_options.all(),
        "valentine_flavours": valentine_flavours,

    }
    return render(request, "store/box-valentines.html", context)


def add_box_to_cart(request):
    form = request.POST
    # print(form)

    if form:
        # get box data
        size = form.get('size', None)
        flavour_format = form.get(FLAVOUR_FORMAT, None)

        # Check if Size obj exists
        if not size:
            return redirect('store:home')
        size_qs = BoxSize.objects.filter(
            active=True, size=size, special_box=False)

        if len(size_qs) != 1:
            return redirect('store:home')
        size_obj = size_qs.first()

        if flavour_format == Box.PRE_BUILT:
            selected_prebuilts = []
            prebuilds = PreBuildFlavour.objects.filter(active=True)
            for obj in prebuilds:
                selected = form.get(obj.slug, None)
                if selected:
                    selected_prebuilts.append(obj)

            # create box
            new_box = Box(size=size_obj, flavour_format=flavour_format)
            new_box.save()
            new_box.selected_prebuilts.set(selected_prebuilts)

        elif flavour_format == Box.PICK_AND_MIX:
            flavours = Flavour.objects.active()
            selected_flavours = []
            for obj in flavours:
                quantity = form.get(obj.slug, 0)
                # print(obj.slug, quantity)
                if quantity and int(quantity) > 0:
                    flavour_choice_obj = FlavourChoice(
                        quantity=quantity, flavour=obj)
                    flavour_choice_obj.save()
                    selected_flavours.append(flavour_choice_obj)

            # print(selected_flavours)

            new_box = Box(size=size_obj, flavour_format=flavour_format)
            new_box.save()
            new_box.selected_flavours.set(selected_flavours)
        else:
            return redirect('store:home')

        # create entry
        box_quantity = form.get('box_quantity', None)
        cart_entry = CartEntry.objects.new(
            request, product=new_box, quantity=box_quantity)
        user_design_id = request.session.get('user_design_id')
        user_design_qs = UserChocolateDesign.objects.filter(
            active=True, id=user_design_id)
        if user_design_qs.count() == 1:
            cart_entry.user_chocolate_design = user_design_qs.first()
        cart_entry.save()

    return redirect('carts:home')


def add_special_box_to_cart(request):
    form = request.POST
    print(form)

    if form:
        # get box data
        slug = form.get('slug', None)
        flavour_format = form.get(FLAVOUR_FORMAT, None)

        # Check if Size obj exists
        if not slug:
            return redirect('store:home')
        slug_qs = BoxSize.objects.filter(active=True, slug=slug)

        if len(slug_qs) != 1:
            return redirect('store:home')
        box_size_obj = slug_qs.first()

        selected_prebuilts = []
        prebuilds = PreBuildFlavour.objects.filter(active=True)
        for obj in prebuilds:
            selected = form.get(obj.slug, None)
            if selected:
                selected_prebuilts.append(obj)

        selected_prebuild_slug = form.get("prebuiltFlavor", None)
        selected_prebuild = PreBuildFlavour.objects.filter(
            active=True, slug=selected_prebuild_slug)

        new_box = Box(size=box_size_obj, flavour_format=flavour_format)
        new_box.save()
        if selected_prebuild:
            # create box
            new_box.selected_prebuilts.set(selected_prebuild)

        # create entry
        box_quantity = form.get('box_quantity', None)
        cart_entry = CartEntry.objects.new(
            request, product=new_box, quantity=box_quantity)
        user_design_id = request.session.get('user_design_id')
        user_design_qs = UserChocolateDesign.objects.filter(
            active=True, id=user_design_id)
        if user_design_qs.count() == 1:
            cart_entry.user_chocolate_design = user_design_qs.first()
        cart_entry.save()

    return redirect('carts:home')


def lot_page(request, size=None):
    prebuilds = PreBuildFlavour.objects.filter(active=True)
    flavours = Flavour.objects.active()
    lot_size_qs = LotSize.objects.filter(size=size)

    obj = None
    if len(lot_size_qs) == 1:
        obj = lot_size_qs.first()

    context = {
        "size": size,
        "flavours": flavours,
        "prebuilds": prebuilds,
        "PRE_BUILT": Lot.PRE_BUILT,
        "PICK_AND_MIX": Lot.PICK_AND_MIX,
        "FLAVOUR_FORMAT": FLAVOUR_FORMAT,
        "title": "LOTS",
        "obj": obj,
    }

    return render(request, "store/lot.html", context)


def add_lot_to_cart(request):
    form = request.POST
    print(form)

    if form:
        # get box data
        size = form.get('size', None)
        flavour_format = form.get(FLAVOUR_FORMAT, None)

        # Check if Size obj exists
        if not size:
            return redirect('store:home')
            print("error 144")
        size_qs = LotSize.objects.filter(active=True, size=size)

        if len(size_qs) != 1:
            return redirect('store:home')
            print("error 148")
        size_obj = size_qs.first()

        if flavour_format == Lot.PRE_BUILT:
            selected_prebuilts = []
            prebuilds = PreBuildFlavour.objects.filter(active=True)
            for obj in prebuilds:
                selected = form.get(obj.slug, None)
                if selected:
                    selected_prebuilts.append(obj)

            # create box
            new_lot = Lot(size=size_obj, flavour_format=flavour_format)
            new_lot.save()
            new_lot.selected_prebuilts.set(selected_prebuilts)

        elif flavour_format == Lot.PICK_AND_MIX:
            flavours = Flavour.objects.active()
            selected_flavours = []
            for obj in flavours:
                quantity = form.get(obj.slug, 0)
                print(obj.slug, quantity)

                if int(quantity) > 0:
                    flavour_choice_obj = FlavourChoice(
                        quantity=quantity, flavour=obj)
                    flavour_choice_obj.save()
                    selected_flavours.append(flavour_choice_obj)

            print(selected_flavours)

            new_lot = Lot(size=size_obj, flavour_format=flavour_format)
            new_lot.save()
            new_lot.selected_flavours.set(selected_flavours)
        else:
            return redirect('store:home')

        # create entry
        cart_entry = CartEntry.objects.new(
            request, product=new_lot, quantity=1)
        print("cart_entry")
        print(cart_entry)

    return redirect('carts:home')


def remove_box_from_cart(request):
    form = request.POST

    if form:
        obj_id = form.get('obj_id', None)
        CartEntry.objects.set_inactive(request, id=obj_id)

    return redirect('carts:home')

def add_product_to_cart(request):

    form = request.POST

    if form:

store/templates/store/advent-calendar.html
{% extends "base.html" %}

{% load static %}

{% block head_title %}{{ box_obj.seo_title }}{% endblock %}
{% block meta_description %}{{ box_obj.seo_description }}{% endblock %}

{% block content %}

{% url 'store:add_boxes' as add_boxes_url %}
{% url 'store:add_boxes_special' as add_boxes_special_url %}

<section class="row">
    <div class="col s12 px-0">
        <div class="inner-banner py-2 valign-wrapper"
             style="
         background-image:url({% static 'images/home/banner-1.jpg' %});
         ">
            <div class="center w-100 white-text p-3 mt-5">
                <h1 class="font-150 mt-5 bold"> Experience 24 Tastes Of Christmas With A CassPea Advent Calendar!</h1>
                <p class="font-150">Pre-Order Yours Today In Time For December 1st!</p>
            </div>
        </div>
        {% include "base/navbar-carousel.html" %}
    </div>
</section>


<div class="container">
    <div class="row mt-5">
        <div class="col s12 m6">
            <div class="owl-carousel owl-theme">
                {% if box_obj.images %}
                {% for obj in box_obj.images %}
                <div class="item">
                    <a class="modal-trigger" href="#modal{{ forloop.counter }}">
                        <img src="{{ obj.url }}" alt="" class="">
                    </a>
                </div>
                {% endfor %}
                {% endif %}
            </div>

            <ul id='box-carousel-dots' class='owl-dots'>
                {% for obj in box_obj.images %}
                <button role="button" class="owl-dot active">
                    <img src="{{ obj.url }}" alt=""
                         class="responsive-img" width="50px">
                </button>
                {% endfor %}

            </ul>
        </div>

        <div class="col s12 m6">
            <h1 class="font-150 bold">{{ box_obj.seo_title }}</h1>
            <p class=" my-orange-text font-150">£{{ box_obj.price }}</p>
            <p>
                We find ourselves at the juncture eagerly awaited by many – the advent of the Christmas holidays. It is
                with great pleasure that we extend an invitation to partake in the festivities, surrounded by dear
                friends and family, and enhance this experience with our innovative Advent Calendar.
            </p>

            <p>
                Our advent calendar is a testament to craftsmanship and holiday spirit. Beyond the mere countdown, it
                offers an immersive experience, with each door revealing not just numbers and riddles, but a curated
                selection of novel flavors and exquisite decorations, thoughtfully crafted for this occasion.
            </p>
            <p>
                This is an opportunity to elevate your holiday traditions to new heights. Secure your advent calendar by
                pre-ordering now, and we guarantee timely delivery, allowing you to commence this enchanting journey on
                December 1st. Prepare to relish the magic of the season, unwrapping a new delight each day.

            <p>
                May your Christmas season be marked by joy and merriment, and may our Advent Calendar enhance every
                moment of this cherished time.
            </p>
            <p class="bold">* Advent Calendars will be shipped from the 24th of November.</p>
            <p>For allergen information please <a class="modal-trigger text-underline my-orange-text"
                                                  href="#allergenModal">
                Click Here</a></p>
            <form method="POST" action="{{ add_boxes_special_url }}"> {% csrf_token %}
                <p class="bold">Quantity</p>
                <div class="row">

                    <div class="col s12">
                        <button class="btn btn-green btn-number"
                                data-type="minus" data-field="box_quantity"
                        >-
                        </button>

                        <input id="box_quantity" type="number"
                               name="box_quantity" class="validate center browser-default"
                               required min="1" value="1" max="100">

                        <button class="btn btn-green btn-number"
                                data-type="plus" data-field="box_quantity"
                        >+
                        </button>
                    </div>


                </div>

                <div class="row">
                    <div class="col s12" id="">
                        <p class="bold">Pick your flavour</p>
                        {% for obj in prebuilds %}
                        <p class="box-flavour-radio">
                            <label>
                                <input class="prebuild-input" name="{{ obj.slug }}" type="checkbox"/>
                                <span>{{ obj.name }}</span>
                            </label>
                        </p>
                        {% endfor %}


                    </div>
                </div>

                <input type="hidden" value="{{ box_obj.slug }}" name="slug">
                <input type="hidden" value="{{ PRE_BUILT }}" name="{{ FLAVOUR_FORMAT }}">

                <p class="center">
                    <button type="submit" id="submit-btn" class="btn-large btn-orange w-100">
                        Add to Cart
                    </button>
                </p>

            </form>
        </div>
    </div>
</div>
</div>


<!--flavours-->
<section class="container">
    <div class="row">
        <div class="col s12 center">
            <p class="font-150 bold">
                Indulge in 24 Christmas Delights, showcasing our cherished signature tastes and an exclusive premiere of
                4 <span class="red-text">BRAND NEW</span> flavours within our <span
                    class="red-text">Advent Calendar</span>
            </p>
        </div>
    </div>
    <div class="row">

        {% for obj in flavours_qs %}
        <div class="col s12 m3">
            <div class="row">
                <div class="col s12 center">
                    {% if obj.image %}
                    <img src="{{ obj.image.url }}" class="responsive-img w-50"/>
                    {% endif %}
                </div>
                <div class="col s12 center">
                    <p class="my-red-text pt-0 mb-0 mt-0 bold">{{ obj.name }}</p>
                    {% if obj.allergens_str %}
                    <p class="mt-0" style="font-size:0.75rem">*Contains {{ obj.allergens_str }}</p>
                    {% endif %}
                </div>
            </div>

        </div>
        {% endfor %}
    </div>
</section>

<!--reviews-->
<div class=" mt-5 reviews-section">
    <div class="container">
        <div class="row">
            <div class="col s12 center">
                <p class="font-200 bold white-text">
                    Customer Experiences
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col s12 m4">
                <div class="review-card">
                    <p class="bold red-text">Thank you for the wonderful chocolates!</p>
                    <p>
                        They arrived this morning. They look amazing! I should have ordered a bigger box.
                        I will leave a review later. What a great talent you and your team have! My husband is a major
                        chocoholic!
                        Many thanks again.
                        #Support small businesses
                        Sabrina Crichlow
                    </p>
                </div>
            </div>
            <div class="col s12 m4">
                <div class="review-card">
                    <p class="bold">Great quality chocolates.</p>
                    <p>
                        They really do look amazing in real life. Taste absolutely divine and a good variety of
                        flavours.
                        Arrived in time for an anniversary present. Love the packaging, expensive quality.
                    </p>
                </div>
            </div>
            <div class="col s12 m4">
                <div class="review-card">
                    <p class="bold my-green-text">The best purchase I’ve made in a long time</p>
                    <p>
                        I tasted casspea chocolates at a fair and was very very impressed. I purchased a box to take to
                        a dinner party
                        and they were an absolute success. I am now a big fan. I think that the fact that all's handmade
                        by one person
                        is incredible. The passion, work, knowledge and dedication that goes into the process of making
                        each one is worthy
                        of praise.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal Structure -->
<div id="allergenModal" class="modal">
    <div class="modal-content">
        <h4>Allergens</h4>
        <img src="{% static 'images/flavours/allergen-table.jpg' %}" alt="allergens" class="responsive-img">
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
    </div>
</div>


<div class="row">
    <div class="col s12">
        {% if box_obj.images %}
        {% for obj in box_obj.images %}
        <div id="modal{{ forloop.counter }}" class="modal">
            <img src="{{ obj.url }}" alt="" class="responsive-img">
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>

<style>
    .modal {
        width:100%!important;
        max-height:unset!important;
        top:20%!important;
        box-shadow:none!important;
        -webkit-box-shadow:none!important;
        background:none!important;
    }

    @media (min-width: 800px) {
        .modal {
            width:48%!important;
            max-height:unset!important;
            top:2%!important;
            box-shadow:none!important;
            -webkit-box-shadow:none!important;
            background:none!important;
        }
    }


</style>

<style>
    .reviews-section {
        background-image: url('/static/images/advent/advent-reviews-bg.jpg');
        background-size: cover;
        background-position: center;
        padding: 50px 0;
        background-attachment: fixed;

    }

    .review-card {
        background: rgba(255, 255, 255, 0.8); /* Adjust opacity as needed (0.8 is semi-transparent) */
        padding: 20px;
        border-radius: 5px;
        margin: 10px;
        text-align: center;
    }

    .review-card p {
        margin: 0;
    }
</style>
{% endblock %}

{% block js_extra %}

<script>


    $('.btn-number').click(function(e){
        e.preventDefault();

        fieldName = $(this).attr('data-field');
        type      = $(this).attr('data-type');
        var input = $("input[name='"+fieldName+"']");
        var currentVal = parseInt(input.val());
        if (!isNaN(currentVal)) {
            if(type == 'minus') {
                if(currentVal > input.attr('min')) {
                    input.val(currentVal - 1).change();
                }

            } else if(type == 'plus') {

                if(currentVal < input.attr('max')) {
                    input.val(currentVal + 1).change();
                }
            }
        } else {
            input.val(0);
        }
    });


    $('.input-number').focusin(function(){
       $(this).data('oldValue', $(this).val());
    });
    $('.input-number').change(function() {

        minValue =  parseInt($(this).attr('min'));
        maxValue =  parseInt($(this).attr('max'));
        valueCurrent = parseInt($(this).val());

        name = $(this).attr('name');
        if(valueCurrent >= minValue) {
            $(".btn-number[data-type='minus'][data-field='"+name+"']").removeAttr('disabled')
        } else {
            alert('Sorry, the minimum value was reached');
            $(this).val($(this).data('oldValue'));
        }
        if(valueCurrent <= maxValue) {
            $(".btn-number[data-type='plus'][data-field='"+name+"']").removeAttr('disabled')
        } else {
            alert('Sorry, the maximum value was reached');
            $(this).val($(this).data('oldValue'));
        }


    });


</script>

{% endblock %}