accounts/passwords/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

urlpatterns = [
    path('password/change/',
         auth_views.PasswordChangeView.as_view(),
         name='password_change'),

    path('password/change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('password/reset/',
         auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('password/reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('password/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),

    path('password/reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('user-list', views.user_list_page, name="user-list"),
    # path('<str:username>', views.detail_page, name="detail"),
]

carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.home_page_v2, name="home"),
    path('agregar', views.agregar_page, name="add"),
    path('borrar', views.delete_entry_page, name="delete_entry"),
    path('add_1', views.add_1_page, name="add_1"),
    path('remove_1', views.remove_1_page, name="remove_1"),
    path('old', views.home_page),

]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('email-test', views.email_test),
    path('address', views.address_page, name="address"),
    path('confirmar', views.confirm_page, name="confirm"),
    path('guess_checkout', views.guess_checkout_page, name="guess_checkout"),
    path('staff-list', views.staff_list_page, name="staff-list"),
    path('list', views.list_page, name="list"),
    path('create-checkout-session', views.CreateCheckoutSessionView.as_view(), name="checkout-session"),
    path('success', views.success_page, name="success"),
    path('cancel', views.cancel_page, name="cancel"),
    path('webhook', views.my_webhook_view, name="webhook"),
    path('staff/<str:order_id>', views.staff_detail_page, name="staff-detail"),
    path('client/<str:order_id>', views.detail_page, name="detail"),
]

accounts/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User


# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


# Create your forms here.

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(label='Email')
    username = forms.CharField(widget=forms.HiddenInput(), required=False)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    def username_clean(self):
        username = self.cleaned_data['email'].lower()
        new = User.objects.filter(username=username)
        if new.count():
            raise ValidationError("User Already Exist")
        return username

    def email_clean(self):
        email = self.cleaned_data['email'].lower()
        new = User.objects.filter(email=email)
        if new.count():
            raise ValidationError(" Email Already Exist")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")
        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['email'],
            self.cleaned_data['email'],
            self.cleaned_data['password1'],
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name']

        )
        return user

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email',)

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib import messages

from carts.models import Cart
from orders.models import Order
from addresses.models import Address

from django.contrib.auth.decorators import login_required

from .forms import CustomUserCreationForm

User = settings.AUTH_USER_MODEL


# Create your views here.
def login_page(request):
    # print(request.user)
    if request.method == "POST":
        next_url = request.POST.get('next_url', None)
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            print("next_url ", next_url is None)
            if next_url is None:
                return redirect('/')
            return redirect(next_url)
    else:
        form = AuthenticationForm(request)
        next_url = request.GET.get('next', "/")

    context = {
        "title": "Log In",
        "form": form,
        "next_url": next_url
    }
    return render(request, "accounts/login.html", context)


def register_page_local(request):
    next_url = request.GET.get('next_url', None)
    if request.method == 'POST':
        next_url = request.POST.get('next_url', None)
        user_form = CustomUserCreationForm(request.POST or None)
        if user_form.is_valid():
            user_obj = user_form.save()
            login(request, user_obj)
            # print(user_obj)
            # print('next_url: ', next_url)
            messages.success(request, 'User created')
            if next_url:
                return redirect(next_url)
            return redirect('/')
        else:
            messages.error(request, 'Error')
    else:
        user_form = CustomUserCreationForm()
    return render(request, 'accounts/register-local.html', {
        "title": "Register",
        'user_form': user_form,
        "next_url": next_url
    })


@staff_member_required
def user_list_page(request):
    User = get_user_model()
    users = User.objects.all()

    context = {
        "users": users,
    }

    return render(request, "accounts/list.html", context)

accounts/templates/accounts/list.html
{% extends "base.html" %}

{% load static %}


{% block head_title %} {% endblock %}

{% block content %}

{% include "base/navbar-dark.html" %}

{% url 'orders:list' as orders_list_url %}


<section class="container">
  <div class="row">
    <div class="col s12">
      <h1 class="font-200 my-4 text-center font-weight-bold text-uppercase">User List</h1>
    </div>
  </div>
</section>

<section class="container">
  <div class="row">
    <div class="col s12">
      <div class="collection">
        <a class="collection-item">
          <div class="row my-orange-text">
            <div class="col s3">
              User
            </div>
            <div class="col s3">
              Email
            </div>

          </div>
        </a>

        {% for user in users %}
        <a href="{{ order.get_absolute_url }}" class="collection-item">
          <div class="row my-grey-text">
            <div class="col s3">
              {{ user.first_name }} {{ user.last_name }}
            </div>
            <div class="col s3">
              {{ user.email }}
            </div>
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block head_title %} Iniciar Sesión | {{ block.super }}{% endblock %}

{% block content %}
{% include "base/inner-banner.html" %}
{% url 'password_reset' as password_reset_url %}


<div class="container my-5">
  <div class="row">
    <div class="col s12">
      <h1 class="font-200 center">Log in CassPea</h1>
    </div>
  </div>
</div>


<div class="container">
  <div class="row my-5">
    <div class="col m6 offset-m3">
      <div class="card p-5">
        <p class="font-150 mt-0">Returning User</p>
        <form method="POST"> {% csrf_token %}

          <div class="input-field">
            {{ form.username }}
            <label for="id_username">Email</label>
          </div>


          <div class="input-field">
          {{ form.password }}
            <label for="id_password">Password</label>
          </div>
          {{ form.non_field_errors }}
          <input type="hidden" name="next_url" value="{{ next_url }}">
          <button type="submit" class="btn-large btn-orange mt-3 w-100">Log in</button>
        </form>
        {% if error %}
        <p class="text-red">{{ error }}</p>
        {% endif %}
        <p class="center"><a class="" href="{{ password_reset_url }}">Reset Password</a></p>
      </div>
      <div class="card p-5">
        <p class="font-150 mt-0">New user?</p>
        <p>
          <a class="btn-large btn-green w-100"
             href="/register{% if next_url %}?next_url={{ next_url }}{% endif %}">
            Register</a>
        </p>

      </div>

    </div>

  </div>
</div>

{% endblock %}

accounts/templates/accounts/register-local.html
{% extends "base.html" %}

{% block content %}
{% include "base/inner-banner.html" %}

<div class="container">
    <div class="row">
        <div class="col s12 m8 offset-m2 mt-5">
            <h1 class="font-200 text-blue center mb-5">Register</h1>
            <form method="post" class="card px-5 py-3">
                {% csrf_token %}
                {{ user_form.as_p }}
                <input type="hidden" name="next_url" value="{{ next_url }}">
                <p class="center">
                    <button type="submit" class="btn-large btn-orange w-100 text-capitalize font-150">
                    Create Account
                </button></p>
            </form>
        </div>
    </div>
</div>

{% endblock %}