carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.home_page_v2, name="home"),
    path('agregar', views.agregar_page, name="add"),
    path('borrar', views.delete_entry_page, name="delete_entry"),
    path('add_1', views.add_1_page, name="add_1"),
    path('remove_1', views.remove_1_page, name="remove_1"),
    path('old', views.home_page),

]

custom_chocolates/urls.py
from django.urls import path

from . import views

app_name = 'custom_chocolates'

urlpatterns = [
    # path('test', views.test_page, name="test"),
    path('', views.home_page, name="home"),
    path('box_size', views.box_size_page, name="box_size"),
    path('box_size/<str:size>', views.add_to_cart_page, name="q"),
    path('design/<str:slug>', views.design_page, name="design_page"),
    path('add_boxes', views.add_box_to_cart, name="add_boxes"),
    path('create_lot', views.create_lot_page, name="create_lot"),
    path('lot/add', views.add_lot_to_cart, name="add_lot"),
    path('lot/<str:size>', views.lot_page, name="lots"),
]

flavours/urls.py
from django.urls import path

from . import views

app_name = 'flavours'

urlpatterns = [
    path('', views.home_page, name="home"),
]

api_urls = [
    path('', views.FlavourListView.as_view(), name='flavour-list'),
]

lots/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from flavours.models import PreBuildFlavour, FlavourChoice
from custom_chocolates.models import UserChocolateDesign
from decimal import Decimal


# Create your models here.
def upload_location(instance, filename):
    return "box-size-img/%s/%s" % (instance.id, filename)


class LotSizeManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class LotSize(models.Model):
    size = models.PositiveIntegerField()
    description = models.TextField(blank=True, null=True)
    price_id = models.CharField(max_length=200, null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=20, blank=True, null=True)
    active = models.BooleanField(default=True)

    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    image = ProcessedImageField(upload_to=upload_location, null=True, blank=True,
                                processors=[ResizeToFill(1500, 998)],
                                format='JPEG',
                                options={'quality': 95})
    image2 = ProcessedImageField(upload_to=upload_location, null=True, blank=True,
                                 processors=[ResizeToFill(1500, 998)],
                                 format='JPEG',
                                 options={'quality': 95})
    image3 = ProcessedImageField(upload_to=upload_location, null=True, blank=True,
                                 processors=[ResizeToFill(1500, 998)],
                                 format='JPEG',
                                 options={'quality': 95})
    image4 = ProcessedImageField(upload_to=upload_location, null=True, blank=True,
                                 processors=[ResizeToFill(1500, 998)],
                                 format='JPEG',
                                 options={'quality': 95})
    image5 = ProcessedImageField(upload_to=upload_location, null=True, blank=True,
                                 processors=[ResizeToFill(1500, 998)],
                                 format='JPEG',
                                 options={'quality': 95})

    def __str__(self):
        return "Lot of {}".format(self.size)

    objects = LotSizeManager()

    def get_absolute_url(self):
        return f"/store/lot/{self.size}"


class LotPriceIds(models.Model):
    title = models.CharField(max_length=100)
    stripe_id = models.CharField(max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    limit = models.PositiveIntegerField(unique=True)

    def __str__(self):
        return self.title


class Lot(models.Model):
    PRE_BUILT = "pre_built"
    CUSTOM = "custom"
    PICK_AND_MIX = "pick_and_mix"

    FLAVOURS_FORMAT_CHOICES = (
        (CUSTOM, "Custom"),
        (PRE_BUILT, "Pre-Built"),
        (PICK_AND_MIX, "Pick and Mix"),
    )

    prebuilt_size = models.PositiveIntegerField(blank=True, null=True)
    flavour_format = models.CharField(max_length=30, choices=FLAVOURS_FORMAT_CHOICES, default=PRE_BUILT)
    # pre_built = models.ForeignKey(PreBuildFlavour, on_delete=models.PROTECT, null=True)
    selected_prebuilts = models.ManyToManyField(PreBuildFlavour, blank=True, related_name="lot_selected_prebuilts")
    selected_flavours = models.ManyToManyField(FlavourChoice, blank=True, related_name="lot_selected_flavours")

    custom_design = models.ForeignKey(UserChocolateDesign, blank=True, null=True, on_delete=models.PROTECT)

    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "Lot of {} Custom Chocolates".format(self.quantity, self.flavour_format)

    @property
    def price(self):
        price = 0.00

        if self.quantity < 100:
            price = 1.2
        elif self.quantity < 300:
            price = 1
        elif self.quantity < 500:
            price = 0.8
        else:
            price = 0.75

        return Decimal(price)

    @property
    def flavours(self):
        if self.flavour_format == Lot.PRE_BUILT:
            return self.selected_prebuilts
        elif self.selected_flavours.exists():
            return self.selected_flavours
        elif self.custom_chocolates_flavours.exists():
            return self.custom_chocolates_flavours

    @property
    def quantity(self):
        size = 0
        if self.flavour_format == Lot.PRE_BUILT:
            size = self.prebuilt_size
        elif self.flavour_format == Lot.PICK_AND_MIX:
            for flavour in self.selected_flavours.all():
                size += flavour.quantity
        return size

    @property
    def get_price_id(self):
        ids = LotPriceIds.objects.all()
        if self.quantity < 100:
            qs = ids.filter(limit=100)
        elif self.quantity < 300:
            qs = ids.filter(limit=300)
        elif self.quantity < 500:
            qs = ids.filter(limit=500)
        else:
            qs = ids.filter(limit=10000)

        if len(qs) == 1:
            obj = qs.first()
            return obj.stripe_id

custom_chocolates/views.py
from django.shortcuts import render, redirect, get_object_or_404
import math
from flavours.models import PreBuildFlavour, Flavour, FlavourChoice

from boxes.models import Box, BoxSize
from carts.models import CartEntry

from store.models import FLAVOURS, FLAVOUR_FORMAT
from lots.models import Lot, LotSize

from .models import ChocolateDesignLayer, ChocolateDesign, UserChocolateDesign


# Create your views here.
def test_page(request):
    design = ChocolateDesign.objects.filter(id=1).first()
    background_options = design.background_options.all()
    layer1_options = design.layer1_options.all()
    layer2_options = design.layer1_options.all()
    layer3_options = design.layer1_options.all()

    context = {
        "design": design,
        "background_options": background_options,
        "layer1_options": layer1_options,
        "layer2_options": layer2_options,
        "layer3_options": layer3_options,

    }

    return render(request, "custom_chocolates/test2.html", context)


def design_page(request, slug=None):
    qs = ChocolateDesign.objects.filter(active=True, slug=slug)

    obj = None
    if len(qs) == 1:
        obj = qs.first()

    if request.method == 'POST':
        form = request.POST
        if form:
            base_id = form.get('base_id', None)
            layer1_id = form.get('layer1_id', None)
            layer2_id = form.get('layer2_id', None)
            layer3_id = form.get('layer3_id', None)
            design = obj
            user_design = UserChocolateDesign(
                design=design,
                base_id=base_id,
                layer1_id=layer1_id,
                layer2_id=layer2_id,
                layer3_id=layer3_id,
            )
            if request.user.is_authenticated:
                user_design.user = request.user
            user_design.save()
            request.session['user_design_id'] = user_design.id

            return redirect('custom_chocolates:box_size')
        else:
            errors = form.errors.as_data()
    # x

    context = {
        "obj": obj,
        # "image_urls": images,
        "title": "Personalise your {} design".format(obj.title)
    }

    return render(request, "custom_chocolates/design.html", context)


def box_size_page(request):
    qs = BoxSize.objects.active()

    user_design_id = request.session.get('user_design_id')
    user_design = get_object_or_404(UserChocolateDesign, id=user_design_id)

    lot_sizes = LotSize.objects.filter(active=True)

    context = {
        "title": "Pick your Box Size",
        "qs": qs,
        "user_design": user_design,
        "lots": lot_sizes,
    }

    return render(request, "custom_chocolates/box_size.html", context)


def add_to_cart_page(request, size=None):
    user_design_id = request.session.get('user_design_id')
    user_design = get_object_or_404(UserChocolateDesign, id=user_design_id)
    prebuilds = PreBuildFlavour.objects.filter(active=True)
    flavours = Flavour.objects.active()
    box_size_qs = BoxSize.objects.filter(size=size)

    box_obj = None
    if len(box_size_qs) == 1:
        box_obj = box_size_qs.first()

    selects_quantities = range(box_obj.custom_chocolates_min, box_obj.custom_chocolates_min + 30)
    quantity_options = []

    for quantity in selects_quantities:
        max_flavours = math.floor(quantity * box_obj.size / 45)
        if max_flavours == 1:
            text = "{} Boxes, pick 1 flavour".format(quantity)
        elif max_flavours >= len(flavours):
            text = "{} Boxes, You can pick all our {} flavours".format(quantity, len(flavours))
        else:
            text = "{} Boxes, pick up to {} flavours".format(quantity, max_flavours)

        quantity_options.append({
            'quantity': quantity,
            'max_flavours': max_flavours,
            'text': text
        })

    # print(quantity_options)

    context = {
        "size": size,
        "flavours": flavours,
        "prebuilds": prebuilds,
        "PRE_BUILT": Box.PRE_BUILT,
        "PICK_AND_MIX": Box.PICK_AND_MIX,
        "FLAVOUR_FORMAT": FLAVOUR_FORMAT,
        "title": "BOXES",
        "box_obj": box_obj,
        "quantity_options": quantity_options,
        "user_design": user_design,
    }

    return render(request, "custom_chocolates/add_to_cart.html", context)


def add_box_to_cart(request):
    user_design_id = request.session.get('user_design_id')
    user_design = get_object_or_404(UserChocolateDesign, id=user_design_id)
    form = request.POST
    # print(form)

    if form:
        # get box data
        print(form)
        size = form.get('size', None)
        flavour_format = form.get(FLAVOUR_FORMAT, None)

        # Check if Size obj exists
        if not size:
            return redirect('store:home')
        size_qs = BoxSize.objects.filter(active=True, size=size)

        if len(size_qs) != 1:
            return redirect('store:home')
        size_obj = size_qs.first()
        new_box = Box(size=size_obj, flavour_format=flavour_format, custom_design=user_design)
        new_box.save()

        if flavour_format == Box.PRE_BUILT:
            selected_prebuilts = []
            prebuilds = PreBuildFlavour.objects.filter(active=True)
            for obj in prebuilds:
                selected = form.get(obj.slug, None)
                if selected:
                    selected_prebuilts.append(obj)

            # create box
            new_box.selected_prebuilts.set(selected_prebuilts)

        elif flavour_format == Box.PICK_AND_MIX:
            flavours = Flavour.objects.active()
            custom_chocolates_flavours = []
            for obj in flavours:
                selected = form.get(obj.slug, None)
                if selected:
                    custom_chocolates_flavours.append(obj)

            print(custom_chocolates_flavours)

            new_box.custom_chocolates_flavours.set(custom_chocolates_flavours)
        else:
            return redirect('store:home')

        # create entry
        box_quantity = form.get('box_quantity', None)
        cart_entry = CartEntry.objects.new(request, product=new_box, quantity=box_quantity)
        cart_entry.save()

    return redirect('carts:home')


def home_page(request):
    designs = ChocolateDesign.objects.filter(active=True)
    context = {
        "title": "Personalise your Chocolates",
        "designs": designs
    }

    return render(request, "custom_chocolates/home.html", context)


def lot_page(request, size=None):
    prebuilds = PreBuildFlavour.objects.filter(active=True)
    flavours = Flavour.objects.active()
    obj = get_object_or_404(LotSize, size=size)

    user_design_id = request.session.get('user_design_id')
    user_design = get_object_or_404(UserChocolateDesign, id=user_design_id)

    context = {
        "size": size,
        "flavours": flavours,
        "prebuilds": prebuilds,
        "PRE_BUILT": Lot.PRE_BUILT,
        "PICK_AND_MIX": Lot.PICK_AND_MIX,
        "FLAVOUR_FORMAT": FLAVOUR_FORMAT,
        "title": "LOTS",
        "obj": obj,
        "user_design": user_design,
    }

    return render(request, "custom_chocolates/lot.html", context)


def create_lot_page(request, size=None):
    prebuilds = PreBuildFlavour.objects.filter(active=True)
    flavours = Flavour.objects.active()

    user_design_id = request.session.get('user_design_id')
    user_design = get_object_or_404(UserChocolateDesign, id=user_design_id)

    context = {
        "flavours": flavours,
        "prebuilds": prebuilds,
        "PRE_BUILT": Lot.PRE_BUILT,
        "PICK_AND_MIX": Lot.PICK_AND_MIX,
        "FLAVOUR_FORMAT": FLAVOUR_FORMAT,
        "title": "LOTS",
        "user_design": user_design,
    }

    return render(request, "custom_chocolates/create_lot.html", context)


def add_lot_to_cart(request):
    user_design_id = request.session.get('user_design_id')
    user_design = get_object_or_404(UserChocolateDesign, id=user_design_id)
    form = request.POST

    if form:
        # get box data

        flavour_format = form.get(FLAVOUR_FORMAT, None)

        new_lot = Lot(flavour_format=flavour_format, custom_design=user_design)
        new_lot.save()

        if flavour_format == Lot.PRE_BUILT:
            selected_prebuilts = []
            prebuilds = PreBuildFlavour.objects.filter(active=True)
            for obj in prebuilds:
                selected = form.get(obj.slug, None)
                if selected:
                    selected_prebuilts.append(obj)

            # create box
            new_lot.selected_prebuilts.set(selected_prebuilts)
            prebuilt_size = form.get('prebuilt-quantity', None)
            new_lot.prebuilt_size = prebuilt_size
            new_lot.save()

        elif flavour_format == Lot.PICK_AND_MIX:
            flavours = Flavour.objects.active()
            selected_flavours = []
            for obj in flavours:
                quantity = form.get(obj.slug, 0)
                print(obj.slug, quantity)

                if quantity and int(quantity) > 0:
                    flavour_choice_obj = FlavourChoice(quantity=quantity, flavour=obj)
                    flavour_choice_obj.save()
                    selected_flavours.append(flavour_choice_obj)

            # print(selected_flavours)
            new_lot.selected_flavours.set(selected_flavours)
        else:
            return redirect('custom_chocolates:home')

        # create entry
        quantity = new_lot.quantity
        cart_entry = CartEntry.objects.new(request, product=new_lot, quantity=quantity)
        cart_entry.save()

    return redirect('carts:home')

custom_chocolates/templates/custom_chocolates/box_size.html
{% extends "base.html" %}

{% load static %}

{% block head_title %}{{ block.super }} Store{% endblock %}
{% block content %}
{% include "base/inner-banner.html" %}
{% url 'custom_chocolates:create_lot' as lots_url %}

<div class="container mt-5">
  <div class="row">
    <div class="col s12">
      <h2 class="bold font-200 center">Your design is ready, now choose your box size</h2>
      <!--      <div class="mx-auto">-->
      <!--        {% include "custom_chocolates/table_user_design_picture.html" with design=user_design %}-->
      <!--      </div>-->
      <p class="center">Minimun order: 45 chocolates</p>
    </div>
  </div>
</div>

<section class="container">
  <div class="row">
    <div class="col s12">
    </div>
    {% for obj in qs %}
    <div class="col s6 m3">

      {% if obj.store_image %}
      <a href="/custom_chocolates/box_size/{{ obj.size }}"><img src="{{ obj.store_image.url }}" class="responsive-img">
      </a>
      {% endif %}
      <p class="center bold">£{{ obj.custom_price }} ea</p>
      <p class="center ">
        <a class="btn btn-outline-{{ obj.color }} w-100" href="/custom_chocolates/box_size/{{ obj.size }}">
          {{ obj }} <span class="d-none d-md-inline-block">Chocolates</span>
        </a>
      </p>
      <p class="center">
        From
        {% if obj.size == 9 %}
        5 Boxes
        {% elif obj.size == 15 %}
        3 Boxes
        {% elif obj.size == 24 %}
        2 Boxes
        {% elif obj.size == 48 %}
        1 Box
        {% endif %}
      </p>
    </div>
    {% endfor %}
  </div>
</section>

<section class="container mt-5">
  <div class="row">
    <div class="col s12 m6">
      <img src="{% static 'images/custom/lots.jpg' %}" class="responsive-img">
    </div>
    <div class="col s12 m6">
      <h2 class="font-200 bold">Need More?</h2>
      <h3 class="font-150 mt-2">Order chocolates without boxes</h3>
      <table>
        <thead>
        <tr>
          <th>Tier</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Flavours</th>
        </tr>
        </thead>

        <tbody>
        <tr>
          <td>1</td>
          <td>0-100</td>
          <td>£1.2 each</td>
          <td>1-2</td>
        </tr>
        <tr>
          <td>2</td>
          <td>101-300</td>
          <td>£1.00 each</td>
          <td>2-6</td>
        </tr>
        <tr>
          <td>3</td>
          <td>301-500</td>
          <td>£0.8 each</td>
          <td>6-10</td>
        </tr>
        <tr>
          <td>4</td>
          <td>500+</td>
          <td>£0.75 each</td>
          <td>10+</td>
        </tr>

        </tbody>
      </table>
      <p class="center"><a href="{{ lots_url }}" class="btn-large btn-primary w-100 my-orange">Pick your chocolates</a></p>
    </div>
  </div>
</section>

{% endblock %}

custom_chocolates/templates/custom_chocolates/create_lot.html
{% extends "base.html" %}

{% load static %}

{% block head_title %}{{ block.super }} Box Flavours{% endblock %}

{% block content %}

{% url 'custom_chocolates:add_lot' as add_lots_url %}
{% url 'flavours:home' as flavours_url %}

{% include "base/inner-banner.html" %}


<div class="container">
  <div class="row">
    <div class="row mt-5">
      <div class="col s12 m4">
        {% include "custom_chocolates/user_design_pic.html" with design=user_design %}
      </div>
      <div class="col s12 m8">
        <h1 class="font-250">Lot of Chocolates</h1>
        <p class="bold">Price per piece</p>
        <ul>
          <li>0 - 100 = ￡1.2</li>
          <li>101 - 300 = ￡1.00</li>
          <li>301 - 500 = ￡0.8</li>
          <li>500+ = ￡0.75</li>
        </ul>

        <form method="POST" action="{{ add_lots_url }}"> {% csrf_token %}

          <div class="row">
            <div class="col s12">
              <p class="bold">Pick your flavour</p>
            </div>
            <div class="col s12 m6">
              <p>
                <label onclick="showPreBuiltCol()" class="btn boxes-radio-green-btn">
                  <input name="{{ FLAVOUR_FORMAT }}" type="radio" value="{{ PRE_BUILT }}"
                         required/>
                  <span>Pre Built</span>
                </label>
              </p>
            </div>
            <div class="col s12 m6">
              <p>
                <label onclick="showPickAndMixCol()" class="btn boxes-radio-green-btn">
                  <input name="{{ FLAVOUR_FORMAT }}" type="radio" value="{{ PICK_AND_MIX }}" required/>
                  <span>Pick and Mix</span>
                </label>
              </p>
            </div>
          </div>
          <div class="row">
            <div class="col s12 m6 offset-m3" id="preBuiltCol">

              <p class="input-field">
                <input id="prebuilt-quantity" type="number"
                       name="prebuilt-quantity" class="validate center" min="50">
                <label for="prebuilt-quantity">How many chocolates?</label>
              </p>
              <p>Flavours</p>
              {% for obj in prebuilds %}
              <p class="box-flavour-radio">
                <label>
                  <input class="" name="{{ obj.slug }}" type="checkbox"/>
                  <span>{{ obj.name }}</span>
                </label>
              </p>
              <hr>
              {% endfor %}
              <span>*Pick as many as you want</span>

            </div>
            <div class="col s12 m12" id="pickAndMixCol">
              <p class="center">Pick 50+ from each flavour, price per piece calculated at the bottom.</p>
              <p class="center">
                <a class="modal-trigger text-underline my-orange-text" href="{{flavours_url}}" target="_blank">
                View Allergen table</a>
              </p>

              <table>
                <thead>
                <tr>
                  <th></th>
                  <th>Flavour</th>
                  <th class="center">Quantity</th>
                </tr>
                </thead>

                <tbody>
                {% for flavour in flavours %}
                <tr>
                  <td width="70px" class="py-0">
                    {% if flavour.image %}
                    <img src="{{ flavour.image.url }}" class="responsive-img" width="50px"/>
                    {% else %}
                    <img src="/media/flavour-img/7/Maracuya.jpg" class="responsive-img"/>
                    {% endif %}
                  </td>
                  <td class="py-0">{{ flavour.name }}</td>
                  <td class="py-0">
                    <div class="row">
                      <div class="col m2 d-none d-md-block">
                        <button class="btn btn-green btn-number flavour-plus10-btn mt-2"
                                data-type="minus-50" data-field="{{ flavour.slug }}"
                        >-50</button>
                      </div>
                      <div class="col s12 m8">
                        <input id="{{ flavour.slug }}" type="number" value="0" min="0" max="10000"
                           name="{{ flavour.slug }}" class="flavour-input validate center">
                      </div>
                      <div class="col m2 d-none d-md-block">
                        <button class="btn btn-green btn-number flavour-plus10-btn mt-2"
                            data-type="plus-50" data-field="{{ flavour.slug }}"
                    >+50
                    </button>
                      </div>
                    </div>
                  </td>
                </tr>
                {% endfor %}
                </tbody>
              </table>

              <p class="bold font-150 center"><span id="total_chocolates">0</span> Chocolates for a total of ￡<span
                      id="total_price">0</span></p>

            </div>
          </div>
          <p class="center">
            <button type="submit" class="btn-large btn-orange" id="submit-btn">Add Chocolates to Cart
            </button>
          </p>
          
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Modal Structure -->
<div id="allergenModal" class="modal">
  <div class="modal-content">
    <h4 class="">Allergens</h4>
    <img src="{% static 'images/flavours/allergen-table.jpg' %}" alt="allergens" class="responsive-img">
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
  </div>
</div>
{% endblock %}

{% block js_extra %}

<script>
  const preBuiltCol = document.getElementById('preBuiltCol')
  const pickAndMixCol = document.getElementById('pickAndMixCol')
  preBuiltCol.style.display = 'none';
  pickAndMixCol.style.display = 'none';

  function showPreBuiltCol() {
      pickAndMixCol.style.display = 'none';
      preBuiltCol.style.display = 'block';
  }

  function showPickAndMixCol() {
    preBuiltCol.style.display = 'none';
    pickAndMixCol.style.display = 'block';
  }

const max = parseInt({{ size }})
const flavourInputs = $('.flavour-input');
const flavourPlusBtns = $('.flavour-plus-btn');
const flavourPlus10Btns = $('.flavour-plus10-btn');
const submitBtn = $('#submit-btn');

const totalChocolates = $('#total_chocolates');
const totalPrice = $('#total_price');

var timer;
var sum = 0;

function estimateTotal (inputs) {
  var new_total = 0;
  inputs.each(function() {
    var inputValue = parseInt($(this).val());
    if (!isNaN(inputValue) && inputValue > 0) {
      new_total += inputValue
    }
  });
  return new_total
}

function estimatePrice(total) {
  var price;
  if (total < 100) {
    price =  total * 1.2
  } else if (total < 300) {
    price = total
  } else if (total < 500) {
    price = total * 0.8
  } else {
    price = total * 0.75
  } 

  return price.toFixed(2)
}

function showtotal () {
  var total = estimateTotal(flavourInputs)
  var price = estimatePrice(total)

  totalChocolates.text(total)
  totalPrice.text(price)
}

flavourInputs.on('input', function() {
  var inputField = $(this); // Store reference to the input field
  var inputValue = inputField.val();
  clearTimeout(timer); // clear the previous timer
  timer = setTimeout(function() {
    if (inputValue < 0 || inputValue < 50) {
      // Display an error message or perform validation logic
      alert('Please enter a 0 or value greater than 50');
      // Clear the input value
      inputField.val('');
    } else {
      // Input value is valid, perform additional logic if needed
    }
    showtotal()
  }, 750); // set a timer delay of 500 milliseconds (0.5 seconds)
  
});


$('.btn-number').click(function(e){
    e.preventDefault();
    fieldName = $(this).attr('data-field');
    type      = $(this).attr('data-type');
    var input = $("input[name='"+fieldName+"']");
    var currentVal = parseInt(input.val());
    console.log(!isNaN(currentVal))
    if (!isNaN(currentVal)) {
        if(type == 'minus-50') {
            if(currentVal >= input.attr('min') + 50) {
                input.val(currentVal - 50).change();
            } else if (currentVal >= input.attr('min')) {
                input.val(0);
            }
        } else if(type == 'plus-50') {
            if(currentVal < input.attr('max')) {
                input.val(currentVal + 50).change();
          }
        }
    } else {
        input.val(0);
    }
    showtotal()
});


$('.input-number').focusin(function(){
   $(this).data('oldValue', $(this).val());
});

$('.input-number').change(function() {

    minValue =  parseInt($(this).attr('min'));
    valueCurrent = parseInt($(this).val());

    name = $(this).attr('name');
    if (valueCurrent >= minValue) {
        $(".btn-number[data-type='minus'][data-field='"+name+"']").removeAttr('disabled')
    } else {
        $(this).val($(this).data('oldValue'));
    }
});


</script>

{% endblock %}

custom_chocolates/templates/custom_chocolates/home.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}{{ title }} | {{ block.super }}{% endblock %}

{% block content %}

{% include "base/inner-banner.html" %}

<div class="container">
  <div class="row">
    <div class="col s12">
      <h4 class="center bold">Pick a design to personalise</h4>
    </div>
  </div>

  <div class="row">
    {% for obj in designs %}
    <div class="col s12 m4">
      <a href="{{ obj.get_absolute_url }}">
        <div>
          {% if obj.featured_design %}
          {% include "custom_chocolates/user_design_pic.html" with design=obj.featured_design %}
          {% endif %}
        </div>
        <p class="center bold font-200">{{ obj }}</p>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

custom_chocolates/templates/custom_chocolates/table_user_design_picture.html
{% load static %}


<div>
  <div class="position-relative">
    <img src="{{ design.base.side_image.url }}" class="custom-side-background-table">
    <img src="{{ design.layer1.side_image.url }}" class="custom-layer-1-table">
    <img src="{{ design.layer2.side_image.url }}" class="custom-layer-2-table">
    <img src="{{ design.layer3.side_image.url }}" class="custom-layer-3-table">
    <img src="{% static 'images/custom/side/shadows.png' %}" class="custom-side-shadows-table">
  </div>
</div>

custom_chocolates/templates/custom_chocolates/user_design_pic.html
{% load static %}
<div>
  <div class="position-relative ">
    <img src="{{ design.base.side_image.url }}" class="responsive-img" id="custom-side-background"
    >
    <img src="{{ design.layer1.side_image.url }}" id="custom-side-layer-1">
    <img src="{{ design.layer2.side_image.url }}" id="custom-side-layer-2">
    <img src="{{ design.layer3.side_image.url }}" id="custom-side-layer-3">
    <img src="{% static 'images/custom/side/shadows.png' %}" id="custom-side-shadows">
  </div>
</div>