carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.home_page_v2, name="home"),
    path('agregar', views.agregar_page, name="add"),
    path('borrar', views.delete_entry_page, name="delete_entry"),
    path('add_1', views.add_1_page, name="add_1"),
    path('remove_1', views.remove_1_page, name="remove_1"),
    path('old', views.home_page),

]

flavours/urls.py
from django.urls import path

from . import views

app_name = 'flavours'

urlpatterns = [
    path('', views.home_page, name="home"),
]

api_urls = [
    path('', views.FlavourListView.as_view(), name='flavour-list'),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('email-test', views.email_test),
    path('address', views.address_page, name="address"),
    path('confirmar', views.confirm_page, name="confirm"),
    path('guess_checkout', views.guess_checkout_page, name="guess_checkout"),
    path('staff-list', views.staff_list_page, name="staff-list"),
    path('list', views.list_page, name="list"),
    path('create-checkout-session', views.CreateCheckoutSessionView.as_view(), name="checkout-session"),
    path('success', views.success_page, name="success"),
    path('cancel', views.cancel_page, name="cancel"),
    path('webhook', views.my_webhook_view, name="webhook"),
    path('staff/<str:order_id>', views.staff_detail_page, name="staff-detail"),
    path('client/<str:order_id>', views.detail_page, name="detail"),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home_page, name="home"),
    path('snacks/<str:slug>', views.snacks_page, name="snacks_page"),
    path('box/add', views.add_box_to_cart, name="add_boxes"),
    path('product/add', views.add_product_to_cart, name="add_product"),
    path('box/add_special', views.add_special_box_to_cart, name="add_boxes_special"),
    path('box/remove', views.remove_box_from_cart, name="remove_boxes"),
    path('luxury-handmade-chocolates/<str:slug>', views.box_page, name="boxes"),
    path('advent-calendar', views.advent_calendar_page, name="boxes-valentines"),
]

flavours/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from imagekit.processors import ResizeToFill
from imagekit.models import ProcessedImageField


# Create your models here.

class AllergenManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class Allergen(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True, max_length=255)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

    objects = AllergenManager()


def upload_location(instance, filename):
    return "flavour-img/%s/%s" % (instance.id, filename)


class FlavourManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class Flavour(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True, max_length=255)

    description = models.TextField(blank=True, null=True)
    mini_description = models.TextField(max_length=80, blank=True, null=True)
    allergens = models.ManyToManyField(Allergen, blank=True)

    image = ProcessedImageField(upload_to=upload_location, null=True, blank=True,
                                processors=[ResizeToFill(1500, 998)],
                                format='JPEG',
                                options={'quality': 95})

    valentines_flavour = models.BooleanField(default=False)

    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

    objects = FlavourManager()

    @property
    def allergens_str(self):
        text = ""
        count = len(self.allergens.all())
        index = 0
        if count == 1:
            text = self.allergens.all().first().name
        elif count > 0:
            for obj in self.allergens.all():
                index += 1
                if index != count:
                    text = text + obj.name
                    if index + 1 != count:
                        text += ", "
                else:
                    text = text + " and " + obj.name + "."
        return text


class FlavourChoice(models.Model):
    flavour = models.ForeignKey(Flavour, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField()
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return "{} of {}".format(self.quantity, self.flavour)


class PreBuildFlavour(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True, max_length=255)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-updated']


def create_flavor_slug(instance, new_slug=None):
    slug = slugify(instance.name)

    if new_slug is not None:
        slug = new_slug

    qs = Flavour.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()

    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance=slug, new_slug=new_slug)

    return slug


def pre_save_flavor_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_flavor_slug(instance)


pre_save.connect(pre_save_flavor_receiver, sender=Flavour)


def create_slug(instance, new_slug=None):
    slug = slugify(instance.name)

    if new_slug is not None:
        slug = new_slug

    qs = PreBuildFlavour.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()

    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance=slug, new_slug=new_slug)

    return slug


def pre_save_pre_build_flavor_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_pre_build_flavor_receiver, sender=PreBuildFlavour)


def create_alergen_slug(instance, new_slug=None):
    slug = slugify(instance.name)

    if new_slug is not None:
        slug = new_slug

    qs = Allergen.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()

    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance=slug, new_slug=new_slug)
    return slug


def pre_save_allergen_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_alergen_slug(instance)


pre_save.connect(pre_save_allergen_receiver, sender=Allergen)

flavours/views.py
from django.shortcuts import render
from .models import Flavour
from rest_framework import generics
from .serializers import FlavourSerializer

# Create your views here.
def home_page(request):
    qs = Flavour.objects.active()

    split_qs = [qs[i:i + 3] for i in range(0, qs.count(), 3)]
    print(split_qs)

    context = {
        "title": 'Our Flavours',
        "qs": qs,
        "split_qs": split_qs,
    }

    return render(request, "flavours/home.html", context)


class FlavourListView(generics.ListAPIView):
    queryset = Flavour.objects.filter(active=True)
    serializer_class = FlavourSerializer

flavours/templates/flavours/home.html
{% extends "base.html" %}

{% load static %}

{% block head_title %}{{ block.super }} Box Flavours{% endblock %}

{% block content %}

{% url 'store:add_boxes' as add_boxes_url %}
{% url 'store:remove_boxes' as remove_boxes_url %}
{% url 'store:home' as store_home_url %}

{% url 'orders:address' as address_url %}
{% url 'carts:home' as cart_url %}


<section class="row">
  <div class="col s12 px-0">
    <div class="inner-banner py-2 valign-wrapper" id="flavour-home-banner">
      <div class="center w-100 white-text">
        <h1 class="font-250"> {{ title }}</h1>
      </div>
    </div>
    {% include "base/navbar-carousel.html" %}
  </div>
</section>

<section class="">
  <div class="row">
    <div class="col s12 m8 offset-m2 my-5">
      <p class="font-150 center">
        Welcome to our flavours page, here we show you all the great flavours that we have. We also include allergenic
        information for your convenience. If you would like further information please click here.
      </p>
      <p class="center">
        <a class="text-underline my-orange-text" href="#allergen-table">View Allergen table</a>
      </p>


    </div>
  </div>
  {% for split in split_qs %}
  <div class="row">
    {% for obj in split %}
    <div class="col s12 m4">
      <div class="row">
        <div class="col s12 center">
          {% if obj.image %}
          <img src="{{ obj.image.url }}" class="responsive-img w-50"/>
          {% endif %}
        </div>
        <div class="col s12 center">
          <h2 class="font-200 my-pink-text pt-0 bold">{{ obj.name }}</h2>
          {% if obj.description %}
          <p>{{ obj.description }}</p>
          {% endif %}
          {% if obj.allergens_str %}
          <p>*Contains {{ obj.allergens_str }}</p>
          {% endif %}
        </div>
      </div>

    </div>
    {% endfor %}
  </div>

  {% endfor %}
  </div>
</section>

<section class="container my-5" id="allergen-table">
  <div class="row">
    <div class="col s12 l8 offset-l2">
      <img src="{% static 'images/flavours/allergen-table.jpg' %}" alt="allergens" class="responsive-img">
    </div>
  </div>

</section>

{% endblock %}

flavours/templates/flavours/mini-section.html
<!--flavours-->
{% if flavours_qs %}
<section class="container py-3">
    <div class="row">
        {% for obj in flavours_qs %}
        <div class="col s6 m3">
            <div class="row">
                <div class="col s12 center">
                    {% if obj.image %}
                    <img src="{{ obj.image.url }}" class="responsive-img w-50"/>
                    {% endif %}
                </div>
                <div class="col s12 center">
                    <p class="my-red-text pt-0 mb-0 mt-0 bold">{{ obj.name }}</p>
                    {% if obj.allergens_str %}
                    <p class="mt-0" style="font-size:0.75rem">*Contains {{ obj.allergens_str }}</p>
                    {% endif %}
                </div>
            </div>

        </div>
        {% endfor %}
    </div>
</section>
{% endif %}